language: java
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install: ./gradlew downloadSdk unzipSdk
script: ./gradlew clean allTests
jdk:
  - oraclejdk8
branches:
  only:
    - master
notifications:
    slack: 'overstory:EXOfUx93B59RgElP7DEQeJTA#marklogic-debugger'
